apiVersion: v1
kind: Pod
metadata:
  name: debug-tools
spec:
  dnsPolicy: Default
  containers:
    - name: debug-container
      image: busybox
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent

    # Debugging container
    - name: dns-debug
      image: busybox
      command: ["/bin/sh", "-c", "while true; do nslookup user-service.default.svc.cluster.local; sleep 10; done"]
      imagePullPolicy: IfNotPresent
