apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Adjust based on your storage requirements
  resources:
    requests:
      storage: 1Gi  # Adjust storage size as needed
