apiVersion: v1
kind: Service
metadata:
  name: panier-service
  labels:
    app: panier-service
spec:
  selector:
    app: panier-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
