apiVersion: v1
kind: Service
metadata:
  name: livraison-service
  labels:
    app: livraison-service
spec:
  selector:
    app: livraison-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: LoadBalancer
