apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: livraison-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: livraison-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
