apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order-service
spec:
  replicas: 2 # Number of instances you want to run
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: yassinehmedi/ruby-services:order-service
          ports:
            - containerPort: 8084
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresdb:5432/ruby1
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: SPRING_APPLICATION_NAME
              value: order-service
