version: '3.8'

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:15.0
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_ROOT_PASSWORD=admin
      - POSTGRES_DB=Ruby1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - "C:/Program Files/PostgreSQL/16/data:/var/lib/postgres"

  eureka-server:
    image: yassinehmedi/ruby-services:eureka-server
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - 8761:8761


  produit-service:
    image: yassinehmedi/ruby-services:produit-service
    container_name: produit-service
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/Ruby1
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    ports:
      - 8083:8083
    depends_on:
      - eureka-server


networks:
  my-network:
    driver: bridge
