apiVersion: apps/v1
kind: Deployment
metadata:
  name: produit-deployment
  labels:
    app: produit-service
spec:
  replicas: 2 # Number of instances you want to run
  selector:
    matchLabels:
      app: produit-service
  template:
    metadata:
      labels:
        app: produit-service
    spec:
      containers:
        - name: produit-service
          image: yassinehmedi/ruby-services:produit-service
          ports:
            - containerPort: 8083
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresdb:5432/ruby1
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: SPRING_APPLICATION_NAME
              value: produit-service
