apiVersion: v1
kind: Service
metadata:
  name: produit-service
  labels:
    app: produit-service
spec:
  selector:
    app: produit-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer
