apiVersion: v1
kind: Service
metadata:
  name: reclamation-service
  labels:
    app: reclamation-service
spec:
  selector:
    app: reclamation-service
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
  type: LoadBalancer
