apiVersion: v1
kind: Service
metadata:
  name: stock-service
  labels:
    app: stock-service
spec:
  selector:
    app: stock-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
