apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
  labels:
    app: stock-service
spec:
  replicas: 2 # Number of instances you want to run
  selector:
    matchLabels:
      app: stock-service
  template:
    metadata:
      labels:
        app: stock-service
    spec:
      containers:
        - name: stock-service
          image: yassinehmedi/ruby-services:stock-service
          ports:
            - containerPort: 8085  # Port your Spring Boot application listens on
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresdb:5432/ruby1
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: SPRING_APPLICATION_NAME
              value: stock-service



