apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stock-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stock-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
